### ISSUE TITLE
Need to be able to save progress

### ISSUE THREAD

**Issue by brettbarbaro** [corredD/mesoscope#4]
Right now I can't save my progress. What I'm trying to do is go through the list and get the correct structures, along with their principalAxis and Offset, which are no longer saved.

Also, I can't export into cellPACK formats, because I'm missing geometries. This is true even if the entries are deselected in the "Include" column. If an entry is deselected, I shouldn't need its geometry. Then I could at least export partially-completed recipes in cellPACK format.

**Comment by corredD** [comment]
fixed
